### ISSUE TITLE
Ignore .map files while deploying 

### ISSUE THREAD

**Issue by VanHinthem** [hso-nn/d365-cli#48]
Ignore .map files while deploying dev build

**Comment by nsteenbeek** [comment]
After a dev build you not only want to ignore .map files, but the whole dist folder, since the JavaScript files ar also incorrect.
In the past the deploy command did the 'build:prod' script, but then the developer had no choice to clean the dist folder to prevent deploying untouched files. So a little bit a conflict between flexibility of developer and fool-proof deployment.
You can change your package.json#deploy script to "npm run build:prod && hso-d365 deploy"
